### ISSUE TITLE
Task priority anomaly 

### ISSUE THREAD

**Issue by Mary62442** [Mary62442/DropdownLoginJquery#1]
Hi Diego, 
After your recent commits I have identified an issue in the task priority of the gulpfile.js.
The two tasks uglifycss and compressjs run in parallel with the webserver task in the default function.
However, because the tasks are not serialised, sometimes compressjs and uglifycss take longer than webserver, therefore leading to the .css and .js files to not be read on the webpage.
Because of this, only the HTML is displayed and the page needs to be reloaded to display the compressed CSS and JS.

**Comment by diegomary** [comment]
Hi Mary,
apologies
I have immediately worked out a solution, please see the gulpfile.js pasted  and reviewed with the correct task priority. This will solve the issue.

...................................
gulpfile.js

let gulp = require('gulp');
let sass = require('gulp-sass');
let webserver = require('gulp-webserver');
let uglify = require('gulp-uglify');
let uglifycss = require('gulp-uglifycss');
let babel = require('gulp-babel');

//In order for tasks to work in sequence
//make sure the tasks return a stream or promise, or handle the callback

gulp.task('uglifycss', ['sass'], ()=> {
 return  gulp.src('css/**/*.css')
   .pipe(uglifycss({
     "maxLineLen": 80,
     "uglyComments": true
   }))
   .pipe(gulp.dest('dist'));
});

// The task that depends on uglifycss task and must be executed first
gulp.task('sass', ()=> {
     return   gulp.src('scss/**/*.scss')
       .pipe(sass()) 
       .pipe(gulp.dest('css'));   
});


gulp.task('watch', ()=> {
   gulp.watch('scss/**/*.scss', ['uglifycss']);
   gulp.watch('scripts/**/*.js', ['compressjs']);
});

gulp.task('webserver', ['uglifycss', 'compressjs'], ()=> {
 gulp.src('./')
   .pipe(webserver({
     livereload: true,
     directoryListing: false,
     open: true
   }));
});

// Javascript minification task
gulp.task('compressjs', (cb) => {
 return gulp.src(['scripts/*.js'])
   .pipe(babel({
     presets: ['env']
   }))
   .pipe(uglify())
   .pipe(gulp.dest('dist'));
   cb   
});


gulp.task('default', ['webserver','watch']);

**Comment by Mary62442** [comment]
Thank you, Diego.
All is working well now.
